### ISSUE TITLE
add to this plugin is a series list component

### ISSUE THREAD

**Issue by Codenator81** [SitesForChurch/oc-sermonmanager#6]
1 other component we need to add to this plugin is a series list component. We need to be able to list the series alphabetically, choose featured series, and list them based on which ones have been contributed to most recently.

Check out the sermon series implementation on this site for examples: Notice the three series on the home page: https://www.lancasterbaptist.org/
And how there is a list of series on the sermon page: http://preaching.lancasterbaptist.org/

A series list component would enable us to add stuff like that to our themes.

**Comment by Codenator81** [comment]
@pastorryanhayden  Needs more details about what featured series mean. And how filter them in list?

**Comment by pastorryanhayden** [comment]
@Codenator81 forget the featured series- it's a solution looking for a problem.
We just need to be able to sort the series chronologically.  (By those who have had sermons added to them most recently.)
